import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Noto_Sans } from 'next/font/google';
import { Roboto } from 'next/font/google';

import './globals.css';

const robotoFont = Roboto({
  weight: '700',
  subsets: ['latin'],
  variable: '--font-roboto',
});

const notoSansFont = Noto_Sans({
  weight: '700',
  subsets: ['latin'],
  variable: '--font-notosans',
});

const interFont = Inter({
  weight: '700',
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${robotoFont.variable} ${interFont.variable} ${notoSansFont.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
